use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'SwiftyNetworkTools_Example' do
  pod 'SwiftyNetworkTools', :path => '../'
  
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

