use_frameworks!

platform :ios, '10.0'

target 'SwiftyNetworkTools_Example' do
  pod 'SwiftyNetworkTools', :path => '../'

  target 'SwiftyNetworkTools_Tests' do
    inherit! :search_paths

    
  end
end
