use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'SwiftyNetworkTools_Example' do
  pod 'SwiftyNetworkTools', :path => '../'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Needed for building for simulator on M1 Macs
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

